require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CragsController, :type => :controller do

  

  before(:suite) do
    DatabaseCleaner.clean_with(:truncation)
  end

  let(:valid_attributes) {
    FactoryGirl.attributes_for(:crag)
  }

  let(:invalid_attributes) {
    FactoryGirl.attributes_for(:crag, name:nil, latitude: nil, longitude: nil, zoom:nil, )
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CragsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  # GET
  describe "GET" do

    before(:each) do
      DatabaseCleaner.strategy = :truncation
      DatabaseCleaner.start
      DatabaseCleaner.clean
    end

    context "index" do
      it "assigns all crags as @crags" do
        crag = Crag.create! valid_attributes
        get :index, {}, valid_session
        expect(assigns(:crags)).to eq([crag])
      end
    end

    describe "show" do
      it "assigns the requested crag as @crag" do
        crag = Crag.create! valid_attributes
        get :show, {:id => crag.to_param}, valid_session
        expect(assigns(:crag)).to eq(crag)
      end
    end

    describe "new" do
      it "assigns a new crag as @crag" do
        get :new, {}, valid_session
        expect(assigns(:crag)).to be_a_new(Crag)
      end
    end

    describe "edit" do
      it "assigns the requested crag as @crag" do
        crag = Crag.create! valid_attributes
        get :edit, {:id => crag.to_param}, valid_session
        expect(assigns(:crag)).to eq(crag)
      end
    end

    describe "json" do
      it "returns a valid json object" do
        region = FactoryGirl.create(:crag, id:1)
        json = get(:getJson, {}, valid_session)
        expect(json).to_not be_nil;
      end

      it "returns a valid json object when given an id" do
        subject = FactoryGirl.create(:crag) 
        json = get(:getJson, {id: subject.territory_id}, valid_session)
        expect(json).to_not be_nil;
      end
    end

  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Crag" do
        expect {
          post :create, {:crag => valid_attributes}, valid_session
        }.to change(Crag, :count).by(1)
      end

      it "assigns a newly created crag as @crag" do
        post :create, {:crag => valid_attributes}, valid_session
        expect(assigns(:crag)).to be_a(Crag)
        expect(assigns(:crag)).to be_persisted
      end

      it "redirects to the created crag" do
        post :create, {:crag => valid_attributes}, valid_session
        expect(response).to redirect_to(Crag.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved crag as @crag" do
        post :create, {:crag => invalid_attributes}, valid_session
        expect(assigns(:crag)).to be_a_new(Crag)
      end

      it "re-renders the 'new' template" do
        post :create, {:crag => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        FactoryGirl.attributes_for(:crag, name:"It's Jimmy!")
      }

      it "updates the requested crag" do
        crag = Crag.create! valid_attributes
        put :update, {:id => crag.to_param, :crag => new_attributes}, valid_session
        crag.reload
        expect(crag.name).to eq("It's Jimmy!")
      end

      it "assigns the requested crag as @crag" do
        crag = Crag.create! valid_attributes
        put :update, {:id => crag.to_param, :crag => valid_attributes}, valid_session
        expect(assigns(:crag)).to eq(crag)
      end

      it "redirects to the crag" do
        crag = Crag.create! valid_attributes
        put :update, {:id => crag.to_param, :crag => valid_attributes}, valid_session
        expect(response).to redirect_to(crag)
      end
    end

    describe "with invalid params" do
      it "assigns the crag as @crag" do
        crag = Crag.create! valid_attributes
        put :update, {:id => crag.to_param, :crag => invalid_attributes}, valid_session
        expect(assigns(:crag)).to eq(crag)
      end

      it "re-renders the 'edit' template" do
        crag = Crag.create! valid_attributes
        put :update, {:id => crag.to_param, :crag => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested crag" do
      crag = Crag.create! valid_attributes
      expect {
        delete :destroy, {:id => crag.to_param}, valid_session
      }.to change(Crag, :count).by(-1)
    end

    it "redirects to the crags list" do
      crag = Crag.create! valid_attributes
      delete :destroy, {:id => crag.to_param}, valid_session
      expect(response).to redirect_to(crags_url)
    end
  end
end
